### PR TITLE
Back button 🎉 

### PR DESCRIPTION
**Pull request by Explosion-Scratch**

### CODE REVIEW

**Comment by retronbv** [comment]
yay

**Comment by retronbv** [comment]
is it tested or no?

**Comment by Explosion-Scratch** [comment]
Nah

**Comment by Explosion-Scratch** [comment]
You can test it if you want, should work (now that I fixed like a gazillion potential errors)

**Comment by retronbv** [comment]
I’ll just merge it bc you usually know what your doing :shipit:

**Comment by Explosion-Scratch** [comment]
lmao

**Comment by Explosion-Scratch** [comment]
I don't _think_ it'll mess things up but you should test

**Pull request merged**
